//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictiveOrdering.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PredictiveDBEntities : DbContext
    {
        public PredictiveDBEntities()
            : base("name=PredictiveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cust_Authenication> Cust_Authenication { get; set; }
        public DbSet<Bundle_Products> Bundle_Products { get; set; }
    
        public virtual ObjectResult<GETBUNDLEPRODUCTS_Result> GETBUNDLEPRODUCTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETBUNDLEPRODUCTS_Result>("GETBUNDLEPRODUCTS");
        }
    }
}
