//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictiveOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust_Authenication
    {
        public string Cust_Id { get; set; }
        public string Cust_Password { get; set; }
    }
}
